name: react-vote packages

on:
  push:
    branches: master
    

jobs:
  install:
    name: deploy-react-vote
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm build
