name: react-vote packages

on:
  push:
    branches: master
    

jobs:
  install:
    name: deploy-react-vote
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn install
      - run: yarn build
